var searchData=
[
  ['a_0',['a',['../class_runge_kutta.html#aa3ca46518b7dee5b8ccf966d2ad6845f',1,'RungeKutta::a'],['../struct_input_parameters.html#a0c70644a2804a12bdea3fdec57950b26',1,'InputParameters::a']]],
  ['adambashforth_1',['AdamBashforth',['../class_adam_bashforth.html',1,'AdamBashforth'],['../class_adam_bashforth.html#aaaee1fabc0fb824696b4a85c8e87c2f6',1,'AdamBashforth::AdamBashforth()'],['../class_adam_bashforth.html#adeef7136b865253fa032a5b18723e95e',1,'AdamBashforth::AdamBashforth(double step_size, double initial_time, double final_time, Eigen::MatrixXd initial_condition, Function function, Eigen::VectorXd beta)'],['../class_adam_bashforth.html#aec2f3b7fbe00084cdd5baf3ffd4f6f73',1,'AdamBashforth::AdamBashforth(double step_size, double initial_time, double final_time, Eigen::MatrixXd initial_condition, Function function)']]],
  ['adambashforth_2eh_2',['AdamBashforth.h',['../_adam_bashforth_8h.html',1,'']]],
  ['adambashforthfoursteps_3',['AdamBashforthFourSteps',['../class_adam_bashforth_four_steps.html',1,'AdamBashforthFourSteps'],['../class_adam_bashforth_four_steps.html#ab82451767a2841be00b513152e8f73ad',1,'AdamBashforthFourSteps::AdamBashforthFourSteps()'],['../class_adam_bashforth_four_steps.html#a669ef06430eac2828d3c0a8f6948ea4f',1,'AdamBashforthFourSteps::AdamBashforthFourSteps(double step_size, double initial_time, double final_time, Eigen::MatrixXd initial_condition, Function function)']]],
  ['adambashforthfoursteps_2eh_4',['AdamBashforthFourSteps.h',['../_adam_bashforth_four_steps_8h.html',1,'']]],
  ['adambashforthonestep_5',['AdamBashforthOneStep',['../class_adam_bashforth_one_step.html',1,'AdamBashforthOneStep'],['../class_adam_bashforth_one_step.html#a60c8937cd81b8a52d9eae5314779c47e',1,'AdamBashforthOneStep::AdamBashforthOneStep()'],['../class_adam_bashforth_one_step.html#adbb738fe6a66d9f650dc1ff800dc21a8',1,'AdamBashforthOneStep::AdamBashforthOneStep(double step_size, double initial_time, double final_time, Eigen::MatrixXd initial_condition, Function function)']]],
  ['adambashforthonestep_2eh_6',['AdamBashforthOneStep.h',['../_adam_bashforth_one_step_8h.html',1,'']]],
  ['adambashforththreesteps_7',['AdamBashforthThreeSteps',['../class_adam_bashforth_three_steps.html',1,'AdamBashforthThreeSteps'],['../class_adam_bashforth_three_steps.html#afc404bc21dc46821a18c1198a7f17f54',1,'AdamBashforthThreeSteps::AdamBashforthThreeSteps()'],['../class_adam_bashforth_three_steps.html#ae1b0ce0d60fba1ac2a1e11acc8139d33',1,'AdamBashforthThreeSteps::AdamBashforthThreeSteps(double step_size, double initial_time, double final_time, Eigen::MatrixXd initial_condition, Function function)']]],
  ['adambashforththreesteps_2eh_8',['AdamBashforthThreeSteps.h',['../_adam_bashforth_three_steps_8h.html',1,'']]],
  ['adambashforthtwosteps_9',['AdamBashforthTwoSteps',['../class_adam_bashforth_two_steps.html',1,'AdamBashforthTwoSteps'],['../class_adam_bashforth_two_steps.html#acc57dba063d1a67f61c735b3923dfe52',1,'AdamBashforthTwoSteps::AdamBashforthTwoSteps()'],['../class_adam_bashforth_two_steps.html#a2cff69a91ed91116126e7ad64a08e543',1,'AdamBashforthTwoSteps::AdamBashforthTwoSteps(double step_size, double initial_time, double final_time, Eigen::MatrixXd initial_condition, Function function)']]],
  ['adambashforthtwosteps_2eh_10',['AdamBashforthTwoSteps.h',['../_adam_bashforth_two_steps_8h.html',1,'']]],
  ['adammoulton_11',['AdamMoulton',['../class_adam_moulton.html',1,'AdamMoulton'],['../class_adam_moulton.html#a7d4c81f2c06b0ae224df48192007cc3d',1,'AdamMoulton::AdamMoulton()'],['../class_adam_moulton.html#aeb11a5b4020e250e950c80ca855da59b',1,'AdamMoulton::AdamMoulton(double step_size, double initial_time, double final_time, Eigen::MatrixXd initial_condition, Function function, Eigen::VectorXd beta)'],['../class_adam_moulton.html#af6fcfdf6bd385fd5e3ab8de386728a3f',1,'AdamMoulton::AdamMoulton(double step_size, double initial_time, double final_time, Eigen::MatrixXd initial_condition, Function function)']]],
  ['adammoulton_2eh_12',['AdamMoulton.h',['../_adam_moulton_8h.html',1,'']]],
  ['alpha_13',['alpha',['../class_multi_step.html#a32225de441d2dbcbb4414ba4d1e72645',1,'MultiStep::alpha'],['../struct_input_parameters.html#a16070327bdab3ea1ceaf4154cfe0dbb9',1,'InputParameters::alpha']]],
  ['and_20future_20works_14',['TODOs and future works',['../index.html#autotoc_md29',1,'']]],
  ['applyfunction_15',['ApplyFunction',['../class_function.html#a4893d9f55a07a4987594211801aaa38a',1,'Function']]],
  ['available_20basic_20functions_16',['Available Basic Functions',['../index.html#autotoc_md11',1,'']]],
  ['available_20methods_17',['Available Methods',['../index.html#autotoc_md13',1,'']]]
];
